col1,col2,col3,col4
Male,25,Approved,IT
Female,35,Rejected,HR
Male,40,Approved,Finance
Female,28,Rejected,IT
Male,30,Approved,HR
Female,45,Rejected,Finance
Male,50,Approved,IT
Female,22,Rejected,HR
Male,33,Approved,Finance
Female,29,Rejected,IT